backend:
  name: github
  repo: gforeroh/web-site-netlify-cms
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Clave de plantilla", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Fecha de publicación", name: "date", widget: "datetime"}
      - {label: "Descripción", name: "description", widget: "text"}
      - {label: "Publicación destacada", name: "featuredpost", widget: "boolean"}
      - {label: "Foto principal", name: "featuredimage", widget: image}
      - {label: "Cuerpo", name: "body", widget: "markdown"}
      - {label: "Etiquetas", name: "tags", widget: "list"}

  - name: "pages"
    label: "Páginas"
    files:
      - file: "src/pages/index.md"
        label: "Página de destino"
        name: "index"
        fields:
          - {label: "Clave de plantilla", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Título, name: title, widget: string}
          - {label: Imagen, name: image, widget: image}
          - {label: Título Cabecera, name: heading, widget: string}
          - {label: SubTítulo, name: subheading, widget: string}
          - {label: Mainpitch, name: mainpitch, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: text}]}
          - {label: Descripción, name: description, widget: string}
          - {label: Introducción, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Principal, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Clave de plantilla", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Título", name: "title", widget: "string"}
          - {label: "Cuerpo", name: "body", widget: "markdown"}
      - file: "src/pages/products/index.md"
        label: "Página de productos"
        name: "products"
        fields:
          - {label: "Clave de plantilla", name: "templateKey", widget: "hidden", default: "product-page"}
          - {label: Título, name: title, widget: string}
          - {label: Imagen, name: image, widget: image}
          - {label: Títuli Cabecera, name: heading, widget: string}
          - {label: Descripción, name: description, widget: string}
          - {label: Introducción, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Principal, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
          - {label: Testimonios, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
          - {label: Imagen completa, name: full_image, widget: image}
          - {label: Precios, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}
  
  - name: "projects"
    label: "Proyectos"
    folder: "src/pages/successStories"
    create: true
    slug: "{{day}}-{{month}}-{{year}}-{{slug}}"
    fields:
      - {label: "Clave de plantilla", name: "templateKey", widget: "hidden", default: "success-stories"}
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Fecha de publicación", name: "date", widget: "datetime"}
      - {label: "Descripción", name: "description", widget: "text"}
      - {label: "Publicación destacada", name: "featuredpost", widget: "boolean"}
      - {label: "Foto principal", name: "featuredimage", widget: image}
      - {label: "Cuerpo", name: "body", widget: "markdown"}
      - {label: "Etiquetas", name: "tags", widget: "list"}

